export const AUTH_USER_STARTED = 'auth/AUTH_USER_STARTED';
export const AUTH_USER_SUCCESS = 'auth/AUTH_USER_SUCCESS';
export const AUTH_USER_ERROR = 'auth/AUTH_USER_ERROR';
export const CREATE_USER_SUCCESS = 'auth/CREATE_USER_SUCCESS';
export const CREATE_USER_FAILURE = 'auth/CREATE_USER_FAILURE';
